[build]
  command = "cd src/lambda/mongodb-graphql && npm i && cd ../../../ && npm run build"
  functions = "src/lambda"
  publish = "build"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/graphql"
to = "/.netlify/functions/mongodb-graphql"
status = 200
force = true