[build]
  command = "cd src/lambda/mongodb-graphql && npm i && cd ../../../ && npm run build"
  functions = "src/lambda"
  publish = "build"

[[redirect]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true